### ISSUE TITLE
The Lat/lon order of the geometry is confusing

### ISSUE THREAD

**Issue by Amaan-Samar** [chrieke/geojson-invalid-geometry#2]
Hi!, I am working with geojson data this library is very helpful. I am facing just one confusion. That is of the lat/lon order.  The library implements the lat/lon order for geometry. But in the documents, I find the lon/lat order. Can you please help with it.

Below is the link to the docs that I am referring to and the image of the point geometry as well.
![image](https://github.com/chrieke/geojson-invalid-geometry/assets/80666102/fb7b96f0-6038-45b3-8d2d-fbebf8a1ba5c)

https://datatracker.ietf.org/doc/html/rfc7946

**Comment by chrieke** [comment]
Hi @Amaan-Samar Not sure what you are refering to. GeoJSON is defined as coordinates of lon, lat. The examples in the repository are standard GeoJSON with that. Some tools or websites use the opposite order. Are you refering to something in the Readme text of this repository etc.?
