### ISSUE TITLE
feature-collection w/ one feature

### ISSUE THREAD

**Issue by jessekrubin** [chrieke/geojson-invalid-geometry#4]
why is `examples/problematic_geometries/problematic_multitype_geometry_with_just_one_geometry.geojson` problematic?

The geojson spec says a feature collection can have 0+ features

**Comment by chrieke** [comment]
Hey, yes you are correct. It's not invalid (not in the invalid category), but listed here as a "problematic" example (problematic category). As a reminder that this case should be handled in your code/tool, which some don't and sometimes fail when feeding in this type.

**Comment by jessekrubin** [comment]
@chrieke thanks for your reply!

I found 2 more problems.

- `examples/invalid_structure/invalid_geometry_geometrycollection_nested.geojson` is totally valid -- you can have nested geometry collections
- `examples/invalid_structure/invalid_geometry_geometrycollection_single.geojson` is also valid -- you can have just one geometry w/ in a geom-collection

**Comment by jessekrubin** [comment]
## structurally invalid

- `examples/invalid_geometries/invalid_less_three_unique_nodes.geojson` should be moved to invalid-structure as it is structurally invalid -- polygon needs at least 4 points regardless of uniqueness 
- `examples/invalid_geometries/invalid_incorrect_geometry_data_type.geojson` should also be moved invalid-structural -- structure is invalid for line string 



## mixed feelings

- `examples/problematic_structure/invalid_crs_defined.geojson` I have mixed feelings on `crs` in geojson as it is technically deprecated, however it is extremely useful when working with other crs-s (no idea how to pluralize that)

**Comment by chrieke** [comment]
Thanks for checking it out and the comments and suggestions! Will have a look on the weekend and get back!

**Comment by jessekrubin** [comment]
@chrieke no problemo! lmk if there is anything I can do to help! thanks for putting this repo together!

**Comment by chrieke** [comment]
Hi @jessekrubin finally got to this, thanks for your comments.


>     examples/invalid_structure/invalid_geometry_geometrycollection_nested.geojson is totally valid -- you can have nested geometry collections
>     examples/invalid_structure/invalid_geometry_geometrycollection_single.geojson is also valid -- you can have just one geometry w/ in a geom-collection


Moved this to problematic section. While they are allowed, the geojson specification recommends against it.

>    To maximize interoperability, implementations SHOULD avoid nested
>    GeometryCollections.  Furthermore, GeometryCollections composed of a
>    single part or a number of parts of a single type SHOULD be avoided
>    when that single part or a single object of multipart type
>    (MultiPoint, MultiLineString, or MultiPolygon) could be used instead.

**Comment by chrieke** [comment]
> examples/problematic_structure/invalid_crs_defined.geojson I have mixed feelings on crs in geojson as it is technically deprecated, however it is extremely useful when working with other crs-s (no idea how to pluralize that)

Renamed to "problematic_crs_defined.geojson". Also moved the section up to the top of the "problematic" section in the Readme, it is important to explain.

**Comment by chrieke** [comment]
>     examples/invalid_geometries/invalid_less_three_unique_nodes.geojson should be moved to invalid-structure as it is structurally invalid -- polygon needs at least 4 points regardless of uniqueness
>     examples/invalid_geometries/invalid_incorrect_geometry_data_type.geojson should also be moved invalid-structural -- structure is invalid for line string
> 

Not sure, guess semantically you could argue both ways. I'd say a specific geometry type is defined in the structure, and the geometry coordinates don't fit that, so for me it makes more sense to put it in the "geometry" category. To also ensure that the structure category only contains obvious "structural" issues. Guess argument works both ways, so you might be right, but I think I prefer it this way.

**Comment by chrieke** [comment]
Thank you very much for the comments and thoughts @jessekrubin some important changes! Will close this then, but feel free to reopen or discuss further! Have a good 2025!

**Comment by jessekrubin** [comment]
@chrieke no problemo! hope you are having a good 2025 as well!
